services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SECRET_KEY_1=${SECRET_KEY_1}
      - SECRET_KEY_2=${SECRET_KEY_2}