services:
  app:
    image: tiagoramirez/java-template-21:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SECRET_KEY_1=${SECRET_KEY_1}
      - SECRET_KEY_2=${SECRET_KEY_2}